### PR TITLE
Adds the quick start sample

### PR DESCRIPTION
**Pull request by gremo**
If you move the sample outside the project root it works, otherwise it doesn't:

nest-winston

### CODE REVIEW

**Comment by Nightbr** [comment]
It works well
image

Here is what I have done:

```
cd sample/001-quick-start
npm install
npm start
npm run start:dev
```

You must cd in the example directory, it's an independent project from your lib ;)

**Comment by gremo** [comment]
Yes that is what I did, but it doesn't work for me. Dunno why!

Can you please try to do first `npm install` in the project root and then `cd sample/001-quick-start` and `npm run start:dev`? I guess it's `mocha` and its types, conflicting with `jest` types.

nest-winston

**Comment by Nightbr** [comment]
Ok got it,

you can add `"skipLibCheck": true` in `sample/001-quick-start/tsconfig.json` or you could refactor your Mocha tests into Jest tests (perhaps in another Issue/PR).

**Comment by gremo** [comment]
@Nightbr setting `skipLibCheck` for every sample seems not right to me :)

Maybe take a look at https://github.com/gremo/nest-winston/pull/325 and feel free to improve it if you are confidenti with Jest, thanks!

**Comment by Nightbr** [comment]
Yep sure `SkipLibCheck` is a workaround. But yes if you have the time to replace mocha by jest it's better 👌👍

**Comment by gremo** [comment]
Closing in favor of https://github.com/gremo/nest-winston/pull/327

**Pull request closed without merging**
