### PR TITLE
feature/add-custom-app-name-for-defalt-nestjs-format

### PR DESCRIPTION
**Pull request by nemanja-mudrinic**
This PR will allow users to declare micro-service instance or app for easier reading and grouping logs

### CODE REVIEW

**Comment by gremo** [comment]
Hi, thanks! Can you please remove the .gitignore commit fix? I'll refactor my gitignore later. ..thanks!

**Comment by nemanja-mudrinic** [comment]
> Hi, thanks! Can you please remove the .gitignore commit fix? I'll refactor my gitignore later. ..thanks!

Sure, here you go

**Comment by gremo** [comment]
Well yep... but you should also remove the .idea files :) Leave only the commit "Add your custom app name inside nestLikeConsoleFormat"

**Comment by nemanja-mudrinic** [comment]
Done

**Pull request merged**
