### PR TITLE
My awesome feature

### PR DESCRIPTION
**Pull request by mohsensaremi**
Add `useColor` option in `nestLikeConsoleFormat`.
Using this option when you want to write logs in text files.

### CODE REVIEW

**Comment by gremo** [comment]
Hi! First thank you for contributing. Mind if I ask you what's the purpose of this PR? I reviewed your code and i can't understand the sentence "When you want to write logs in text files".... usually we do this using a custom transport (check the examples).

At the best of my knowledge there is no need to actually implement this at code-level. @TrejGun you agree, am I missing something?

**Comment by mohsensaremi** [comment]
Yes, you are right. We use custom transport for logging in files. I'm using `winston-daily-rotate-file` to write logs in the file.
But I like to write logs in files in NestJs format with utility function `nestWinstonModuleUtilities.format.nestLike()`.
The problem is when you write logs with colors in files, you can not see them properly.
The log file looks like this:

Screen Shot 1400-06-02 at 09 11 57

But when you disable all fancy coloring stuff the output looks like this:

Screen Shot 1400-06-02 at 09 12 43

the purpose of `useColor` option is to write raw text in log files.

**Comment by gremo** [comment]
Thanks for the explanation! Now I understand. Can you post the configuration of the logger (transport etc.) when using this method?

**Comment by mohsensaremi** [comment]
A normal configuration for logging in console only looks like this:
```
@Module({
  imports: [
    WinstonModule.forRoot({
      transports: [
        new winston.transports.Console({
          format: winston.format.combine(
            winston.format.timestamp(),
            winston.format.ms(),
            nestWinstonModuleUtilities.format.nestLike(),
          ),
        }),
      ],
    }),
  ],
})
export class LogModule {}
```

With `winston-daily-rotate-file` transport the configuration looks like this:
```
@Module({
  imports: [
    WinstonModule.forRoot({
      transports: [
        new winston.transports.Console({
          format: winston.format.combine(
            winston.format.timestamp(),
            winston.format.ms(),
            nestWinstonModuleUtilities.format.nestLike(),
          ),
        }),
        new winston.transports.DailyRotateFile({
          filename: 'logs/application-%DATE%.log',
          datePattern: 'YYYY-MM-DD',
          maxSize: '100m',
          maxFiles: '14d',
          format: winston.format.combine(
            winston.format.timestamp(),
            winston.format.ms(),
            nestWinstonModuleUtilities.format.nestLike('NestWinston', {useColor: false}),
          ),
        }),
      ],
    }),
  ],
})
export class LogModule {}
```

As you can see when I use `new winston.transports.DailyRotateFile` transport, in `format` field I used `nestWinstonModuleUtilities.format.nestLike('NestWinston', {useColor: false})` with `{useColor: false}` option to disable coloring in text files.

**Comment by gremo** [comment]
Perfect! Can you please double check the commit, as tests don't cover this part? Then I'll merge and download it and maybe do some minor changes (code formatting maybe because you used JetBrains).

**Comment by mohsensaremi** [comment]
I added `boots successfully with nestLikeConsoleFormat format` test case with two transport.
One with default values and one with the `useColor` option.

**Pull request closed without merging**
