### PR TITLE
refactor: add Git Action Tests

### PR DESCRIPTION
**Pull request by ubudragon**
Move from travis to GH actions

### CODE REVIEW

**Comment by TrejGun** [comment]
@gremo small contribution from our studio to open source
thanks for your lib

**Comment by predam** [comment]
Thanks guys! 

#368

**Comment by gremo** [comment]
Thank you! ❤️ Just to be sure, Git actions would completly replace Travis and the Renovate bot will continue to work (that is, automerge will work because the CI), right?

**Comment by TrejGun** [comment]
yes
and you will have 2000 mins for GH actions every month

**Pull request merged**
