### PR TITLE
Feat/allow to specify winston instance

### PR DESCRIPTION
**Pull request by GuillaumeDecMeetsMore**
Hello, this PR is related to https://github.com/gremo/nest-winston/issues/480.

I just made the basic changes to make it works. Feel free to add readme documentation or other stuff in this PR.

Thanks !

### CODE REVIEW

**Comment by gremo** [comment]
HI! Thank you for this feature! 😄 

Can you please change README to document the new option an squash all commits into one, as I can review it as a whole?

**Comment by GuillaumeDecMeetsMore** [comment]
@gremo I updated the README and squashed into one commit 😉

**Comment by gremo** [comment]
Can we rename the option `winstonInstance `to just `instance`? WDYT? Then we'll ready to merge, thanks.

**Comment by GuillaumeDecMeetsMore** [comment]
Yeah sure, sounds good to me as well. I have just updated the PR to reflect this

**Comment by gremo** [comment]
Done, will be in 1.8.0

**Pull request merged**
