### PR TITLE
export WinstonLogger

### PR DESCRIPTION
**Pull request by TrejGun**
case with 
```
import {Logger} from "winston";
import {WINSTON_MODULE_PROVIDER} from "nest-winston";

@Inject(WINSTON_MODULE_PROVIDER) private readonly logger: Logger,
```
works good 

but when I want to use
```
@Inject(WINSTON_MODULE_NEST_PROVIDER) private readonly logger: WinstonLogger,
```
`WinstonLogger` is not exported from `nest-winston`, and even `LoggerService` is not exported from `@nestjs/core` so there is no suitable type :(

### CODE REVIEW

**Comment by gremo** [comment]
AFAIK, `WINSTON_MODULE_NEST_PROVIDER` should be used only when using as main Nest logger. @Piranit @jacob87o2 @kierans anyone?

**Comment by TrejGun** [comment]
as I said in #73 there is no easy way to print Error with stack trace using `WINSTON_MODULE_PROVIDER` 
so if you dont want make `WINSTON_MODULE_NEST_PROVIDER` public you have to consider to rework `utilities.format.nestLike` to print error the way nest does it

**Comment by jacob87o2** [comment]
@TrejGun `LoggerService` is exported from `@nestjs/common`, not `@nestjs/core`. 

I use it as main app logger, like so: 
```ts
import { LoggerService } from '@nestjs/common';
(...)
const logger = app.get<LoggerService>(WINSTON_MODULE_NEST_PROVIDER);
app.useLogger(logger);
```
I'm not sure yet, which approach is better - using nest logger provider, or winston logger directly.

**Comment by TrejGun** [comment]
@jacob87o2 oh nice! this could be a solution.
I personally prefer solution which requires less efforts. so for now this is nest logger. 
there is my winston config in #73 which neither looks clean nor does it's work properly in all cases
thats why there is reason to work more on `utilities.format.nestLike`

**Pull request closed without merging**
