### PR TITLE
Add format.ms() supports

### PR DESCRIPTION
**Pull request by tmkx**

### CODE REVIEW

**Comment by gremo** [comment]
Hi! Thanks, can you please elaborate this? Where ms came from? Does it work with previous version of winston?

**Comment by tmkx** [comment]
> Hi! Thanks, can you please elaborate this? Where ms came from? Does it work with previous version of winston?
@gremo 

https://github.com/winstonjs/winston#streams-objectmode-and-info-objects
winston.format.ms()

For example:
```javascript
new winston.transports.Console({
  handleExceptions: true,
  format: winston.format.combine(
    winston.format.timestamp(),
    winston.format.ms(),
    nestWinstonModuleUtilities.format.nestLike('Dashboard'),
  ),
}),
```

Nest Log:
> [Nest] 60361   - 2021-04-29 10:22:03 PM   [NestFactory] Starting Nest application...
> [Nest] 60361   - 2021-04-29 10:22:03 PM   [InstanceLoader] PassportModule dependencies initialized *+157ms*
> [Nest] 60361   - 2021-04-29 10:22:03 PM   [InstanceLoader] CacheModule dependencies initialized *+1ms*
> [Nest] 60361   - 2021-04-29 10:22:03 PM   [InstanceLoader] JwtModule dependencies initialized *+1ms*
> [Nest] 60361   - 2021-04-29 10:22:03 PM   [InstanceLoader] HttpModule dependencies initialized *+1ms*

**Comment by tmkx** [comment]
> Hi! Thanks, can you please elaborate this? Where ms came from? Does it work with previous version of winston?

Hi, anything problem ?

**Comment by gremo** [comment]
Hi, I missed your comment of yesterday sorry 😄 

It seems just fine to me, can you please update the README to use this new option?

**Comment by tmkx** [comment]
> Hi, I missed your comment of yesterday sorry 😄
> 
> It seems just fine to me, can you please update the README to use this new option?

Done  ; )

**Pull request merged**
