### PR TITLE
ft- (add documentation for logger methods)

### PR DESCRIPTION
**Pull request by faithfulojebiyi**
This pull request adds documentation reference for logger methods

### CODE REVIEW

**Comment by gremo** [comment]
Thank you! I need to ask to rebase your work. While you were writing this PR, i force-pushed the same commit to fix GitHub actions. Thanks!

**Comment by gremo** [comment]
Also Renovate bot is now running all the PR and auto-merging them. So you need to wait a bit before rebasing 😄 sorry!

**Comment by faithfulojebiyi** [comment]
@gremo  rebase done

**Comment by gremo** [comment]
Thanks but I think it's not rebase, I can see a lot of push and file changes shows 2?

**Comment by faithfulojebiyi** [comment]
Let me close this and make a new pr

**Pull request closed without merging**
