### PR TITLE
Added type for logger message

### PR DESCRIPTION
**Pull request by reediculous456**
Adding this type makes it easier for the user to understand how to use the logger functions (either a string message or an object with a ` message` property and context items)

### CODE REVIEW

**Comment by reediculous456** [comment]
Ping

**Comment by reediculous456** [comment]
Ping

**Comment by gremo** [comment]
IS changing the signature of the super class `LoggerService` allowed?

**Comment by reediculous456** [comment]
Since it’s just a type change it’s doesn’t really change the signature as far as the runtime is concerned. It does stop any linters from complaining about the use of any here and help users understand what data to put here

**Comment by gremo** [comment]
Does Nest itself change the signature for his own implementation or other similar libraries do the same? I'm not against this change but I have some serious doubts...

**Pull request closed without merging**
