### PR TITLE
Update winston.classes.ts

### PR DESCRIPTION
**Pull request by guillaumeidruide**
Modification to authorize the modification of the level in the method log by keeping the level info by default

### CODE REVIEW

**Comment by gremo** [comment]
Hi @guillaumeidruide , can you explain me why this is necessary?

**Comment by guillaumeidruide** [comment]
Hi, it's to specify in the log the use of a particular level as auditlog, and to keep the logic present in winstonjs inside the definition of the log method

**Comment by gremo** [comment]
OK, please send me a link to the winston documentation, on how to use that argument. By the way, why you only modified the `log` function and not here: https://github.com/gremo/nest-winston/blob/7538cabe69516a60e0e386815bf924cbb40bea6b/src/winston.classes.ts#L34 or other methods?

**Comment by jbpin** [comment]
Hi @gremo,

I'm a coworker of @guillaumeidruide. We need to explain a bit more about the change in order to understand what we try to achieve. 

NestJS interface for the LoggerService is describe here: https://docs.nestjs.com/techniques/logger#custom-implementation
We saw that log correspond for them to a level that you basically translate to the info level. 

In winston, the `log` is a method that can accept a level in the first parameter. See
https://github.com/winstonjs/winston#using-logging-levels

This PR is a proposal to support the `log` method of winston in a the generic `log` of Nestjs and add support for others log levels proposed by the winston library. 
By default the log will log at info level but we can specify a log level to override this behavior. 
Also, others method of the LoggerService are shortcut to predefined level, `error`, `warn`, etc. 

Without this PR, there is no way to write a `emerg`, `alert`, `crit` nor `notice`  log.

I hope this explanation will help you understand more about the context of this PR.

**Comment by jbpin** [comment]
Do we have any update on this PR please ?

**Comment by Errichamonda** [comment]
Any update? This it's the only thing that it's not allowing me and my company to use this package.

**Comment by jbpin** [comment]
@gremo could you please decide what do to with this PR. I need your decision to go further. Thanks

**Pull request closed without merging**
